config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'municipality_residents#index'

  resources :municipality_residents

  post '/municipality_resident/:id/status', to: 'municipality_residents#change_status', as: 'municipality_status'
  get 'search', to: 'search#el_search', as: 'el_search'
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :municipality_resident

  validates :zip_code, :address1, :neighborhood, :city, :uf, presence: true

  enum uf: {
    'AC, Acre': 0,
    'AL, Alagoas': 1,
    'AP, Amapá': 2,
    'AM, Amazonas': 3,
    'BA, Bahia': 4,
    'CE, Ceará': 5,
    'DF, Distrito Federal': 6,
    'ES, Espirito Santo': 7,
    'GO, Goiás': 8,
    'MA, Maranhão': 9,
    'MS, Mato Grosso do Sul': 10,
    'MT, Mato Grosso': 11,
    'MG, Minas Gerais': 12,
    'PA, Pará': 13,
    'PB, Paraíba': 14,
    'PR, Paraná': 15,
    'PE, Pernambuco': 16,
    'PI, Piauí': 17,
    'RJ, Rio de Janeiro': 18,
    'RN, Rio Grande do Norte': 19,
    'RS, Rio Grande do Sul': 20,
    'RO, Rondônia': 21,
    'RR, Roraima': 22,
    'SC, Santa Catarina': 23,
    'SP, São Paulo': 24,
    'SE, Sergipe': 25,
    'TO, Tocantins': 26
  }, _prefix: :currently_uf

  enum ibge_code: {
    'nenhum': nil,
    '12': 0,
    '27': 1,
    '16': 2,
    '13': 3,
    '29': 4,
    '23': 5,
    '53': 6,
    '32': 7,
    '52': 8,
    '21': 9,
    '51': 10,
    '50': 11,
    '31': 12,
    '15': 13,
    '25': 14,
    '41': 15,
    '26': 16,
    '22': 17,
    '24': 18,
    '43': 19,
    '33': 20,
    '11': 21,
    '14': 22,
    '42': 23,
    '35': 24,
    '28': 25,
    '17': 26
  }, _prefix: :currently_ibge
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/municipality_resident.rb
# frozen_string_literal: true

require 'uploaders/image_uploader'
require 'services/cns'

class MunicipalityResident < ApplicationRecord
  searchkick callbacks: :async
  include Uploaders::ImageUploader::Attachment(:image)
  include BaseErrors
  include TwilioClient

  has_one :address
  accepts_nested_attributes_for :address

  validates :full_name, :email, :birthday, :phone_number, :cpf, :cns, :image_data, presence: true
  validates :cpf, uniqueness: { case_sensitive: false }
  validates :phone_number, format: { with: /\A[0-9]{11}\z/, message: I18n.t('errors.messages.allow_digits') }
  validate :valid_cpf?, :valid_birthday?, :valid_email?, :valid_cns?

  after_create :delivery_messages_create
  after_update :delivery_messages_update

  private

  def valid_cpf?
    add_errors(:cpf, 'invalid') unless CPF.valid?(cpf)
  end

  def valid_birthday?
    add_errors(:birthday, 'invalid') if birthday.to_s >= Date.current.to_s
  end

  def valid_email?
    add_errors(:email, 'invalid') unless email =~ URI::MailTo::EMAIL_REGEXP
  end

  def valid_cns?
    add_errors(:cns, 'invalid') unless Services::Cns.validate(cns)
  end

  def delivery_messages_create
    call_message(I18n.t('sms.messages.registered_successfully'))
  end

  def delivery_messages_update
    return unless updated_at_previously_changed?

    call_message(I18n.t('sms.messages.updated_data'))
  end

  def call_message(message)
    send_message(body: message, to: "+55#{phone_number}")

    ApplicationMailer.send_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/municipality_residents_controller.rb
# frozen_string_literal: true

class MunicipalityResidentsController < ApplicationController
  before_action :set_municipality_resident, only: %i[show edit update change_status]

  def index
    @municipality_residents = if params[:search].present?
                                MunicipalityResident.search(params[:search]).results
                              else
                                MunicipalityResident.search('*').results
                              end
  end

  def show; end

  def new
    @municipality_resident ||= MunicipalityResident.new
    @municipality_resident.build_address
  end

  def edit; end

  def create
    @municipality_resident = MunicipalityResident.new(municipality_resident_params)

    respond_to do |format|
      if @municipality_resident.save
        format.html { redirect_to municipality_residents_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @municipality_resident.update(municipality_resident_params)
        format.html { redirect_to municipality_resident_url(@municipality_resident) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def change_status
    @municipality_resident.active = !@municipality_resident.active?
    redirect_to municipality_residents_path if @municipality_resident.save
  end

  private

  def set_municipality_resident
    @municipality_resident = MunicipalityResident.find(params[:id])
  end

  def municipality_resident_params
    params.require(:municipality_resident).permit(:full_name, :cpf, :cns, :email, :birthday, :phone_number,
                                                  :image, :image_data, :active, address_attributes: %i[
                                                    id zip_code address1 complement neighborhood city uf ibge ibge_code
                                                  ])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/municipality_residents_helper.rb
# frozen_string_literal: true

module MunicipalityResidentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunicipalityRegistration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/municipality_residents/_form.html.erb
  <%= form_with(model: municipality_resident) do |form| %>
    <% if municipality_resident.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(municipality_resident.errors.count, "error") %> não é possível salvar </h2>

          <ul>
            <% municipality_resident.errors.each do |error| %>
            <div class=”alert alert-primary” role=”alert”>
              <li><%= error.full_message %></li>
            </div>
            <% end %>
          </ul>
        </div>
    <% end %>
      <div class='form-group'>
        <div class="row">
          <div class="col">
            <%= form.label t('full_name'), style: "display: block" %>
            <%= form.text_field :full_name, class: "form-control" %>
          </div>

          <div class="col">
            <%= form.label :cpf, style: "display: block" %>
            <%= form.text_field :cpf, class: "form-control" %>
          </div>

          <div class="col">
            <%= form.label :cns, style: "display: block" %>
            <%= form.text_field :cns, class: "form-control" %>
          </div>

          <div class="col">
            <%= form.label :email, style: "display: block" %>
            <%= form.text_field :email, class: "form-control" %>
          </div>

          <div class="col">
            <%= form.label t('birthday'), style: "display: block" %>
            <%= form.date_select :birthday, :start_year => Date.current.year, :end_year => 1920 %>
          </div>

          <div class="col">
            <%= form.label t('phone_number'), style: "display: block" %>
            <%= form.text_field :phone_number, class: "form-control" %>
          </div>

          <div class="col">
            <%= form.label t('image_data') %>
            <%= form.file_field :image, class: "form-control" %>
          </div>
          <div class="address_form">
            <h2>Endereço</h2>
            <%= form.fields_for :address do |address_form| %>
              <div class="row">
                <div class="col">
                  <%= address_form.label t('city') %>
                  <%= address_form.text_field :city, class: "form-control" %>
                </div>
                <div class="col">
                  <%= address_form.label t('zip_code') %>
                  <%= address_form.text_field :zip_code, class: "form-control" %>
                </div>
                <div class="col">
                  <%= address_form.label t('address_1') %>
                  <%= address_form.text_area :address1, size: '70x5', class: "form-control" %>
                </div>
                <div class="col">
                  <%= address_form.label t('Neighborhood') %>
                  <%= address_form.text_field :neighborhood, class: "form-control" %>
                </div>
                <div class="col">
                  <div class="list-group">
                    <%= address_form.label :uf %>
                    <%= address_form.select :uf, Address.ufs.keys %>
                  </div>
                </div>
                <div class="col">
                  <%= address_form.label t('complement') %>
                  <%= address_form.text_field :complement, class: "form-control" %>
                </div>
                <div class="col">
                  <div class="list-group">
                    <%= address_form.label :ibge %>
                    <%= address_form.select :ibge, Address.ibge_codes.keys%>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <div class="form-group">
      <%= form.submit t('create_municipality'), class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/municipality_residents/_municipality_resident.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm fs--1 mb-0" id="municipality_residents">
    <thead>
      <tr>
        <th> ID </th>
        <th> Name </th>
        <th> CPF </th>
        <th> CNS </th>
        <th> Telefone </th>
        <th> Email </th>
        <th> Active? </th>
        <th> City </th>
        <th> CEP </th>
        <th> END: </th>
        <th> Neighborhood </th>
        <th> UF </th>
        <th> complement </th>
        <th> ibge </th>
      </tr>
    </thead>
    <tbody>
      <% address = municipality_resident.address %>
      <tr>
        <td><%= municipality_resident.id %></td>
        <td><%= municipality_resident.full_name %></td>
        <td><%= "#{municipality_resident.cpf.first(3)}.***.***-#{municipality_resident.cpf.last(2)}"%></td>
        <td><%= "#{municipality_resident.cns.first(3)}************"%></td>
        <td><%= "(#{municipality_resident.phone_number.first(2)}) *****-#{municipality_resident.phone_number.last(4)}"%></td>
        <td><%= municipality_resident.email %></td>
        <td><%= municipality_resident.active? %></td>
        <td> <%= address&.city %> </td>
        <td> <%= address&.zip_code %> </td>
        <td> <%= address&.address1 %> </td>
        <td> <%= address&.neighborhood %> </td>
        <td> <%= address&.uf %> </td>
        <td> <%= address&.complement %> </td>
        <td> <%= address&.ibge %> </td>
      </tr>
    </tbody>
  </table>
</div>


<style>
  #municipality_residents {
    font-family: Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 50px
  }

  #municipality_residents td, #municipality_residents th {
    border: 1px solid #ddd;
    padding: 8px;
  }

  #municipality_residents tr:nth-child(even){background-color: rgb(234, 232, 232);}

  #municipality_residents tr:hover {background-color: rgb(147, 133, 174);}

  #municipality_residents th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: rgb(54, 79, 96);
    color: white;
  }
</style>

app/views/municipality_residents/edit.html.erb
<h1><%= t('editing_municipality_resident')%></h1>

<%= render "form", municipality_resident: @municipality_resident %>

<br>

<div>
  <%= button_to t("show_municipality"), @municipality_resident, method: :get, class: "btn btn-dark" %>
  <%= button_to t("back_to_municipalities"), municipality_residents_path, method: :get, class: "btn btn-success" %>
</div>

app/views/municipality_residents/index.html.erb
<div class="table-responsive">
  <h1>Lista de Municipes</h1>

  <%= form_with url: municipality_residents_path, method: :get do |f| %>
    <%= f.text_field :search, class: "form-control-sm" %>
    <%= f.hidden_field :model, value: :municipality_resident %>
    <%= f.submit t('search'), class: "btn btn-primary" %>
  <% end %>
  <%= button_to "Criar novo Municipe", new_municipality_resident_path, class: "btn btn-success", method: :get %>
  <table class="table table-striped table-sm fs--1 mb-0" id="municipality_residents">
    <thead>
      <tr>
        <th> ID </th>
        <th> Name </th>
        <th> CPF </th>
        <th> CNS </th>
        <th> Telefone </th>
        <th> Email </th>
        <th> Active? </th>
        <th> City </th>
        <th> CEP </th>
        <th> END: </th>
        <th> Neighborhood </th>
        <th> UF </th>
        <th> complement </th>
        <th> ibge </th>
        <th> Options </th>
      </tr>
    </thead>
    <tbody>
      <% @municipality_residents.each do |municipality_resident| %>
      <% address = municipality_resident.address %>
      <tr>
        <td><%= municipality_resident.id %></td>
        <td><%= municipality_resident.full_name %></td>
        <td><%= "#{municipality_resident.cpf.first(3)}.***.***-#{municipality_resident.cpf.last(2)}"%></td>
        <td><%= "#{municipality_resident.cns.first(3)}************"%></td>
        <td><%= "(#{municipality_resident.phone_number.first(2)}) *****-#{municipality_resident.phone_number.last(4)}"%></td>
        <td><%= municipality_resident.email %></td>
        <td><%= municipality_resident.active? %></td>
        <td> <%= address&.city %> </td>
        <td> <%= address&.zip_code %> </td>
        <td> <%= address&.address1 %> </td>
        <td> <%= address&.neighborhood %> </td>
        <td> <%= address&.uf %> </td>
        <td> <%= address&.complement %> </td>
        <td> <%= address&.ibge %> </td>
        <td>
          <div class='form-group'>
            <div class="row">
              <div class="col">
                <%= button_to t("show_municipality"), municipality_resident, method: :get, class: "btn btn-dark" %>
              </div>
              <div class="col">
                <%= button_to "Editar", edit_municipality_resident_path(municipality_resident.id), method: :get, class: "btn btn-warning" %>
              </div>
              <div class="col">
                <%= button_to municipality_resident.active? ? "Desativar" : "Ativar", municipality_status_path(municipality_resident.id), class: "btn btn-danger", method: :post %>
              </div>
            </div>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<style>
  #municipality_residents {
    font-family: Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 50px
  }

  #municipality_residents td, #municipality_residents th {
    border: 1px solid #ddd;
    padding: 8px;
  }

  #municipality_residents tr:nth-child(even){background-color: rgb(234, 232, 232);}

  #municipality_residents tr:hover {background-color: rgb(147, 133, 174);}

  #municipality_residents th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: rgb(110, 59, 182);
    color: white;
  }
</style>

app/views/municipality_residents/new.html.erb
<h1><%= t('new_municipality_resident') %></h1>

<%= render "form", municipality_resident: @municipality_resident %>

<br>

<div>
  <%= button_to "Back to municipality residents", municipality_residents_path, method: :get, class: "btn btn-dark" %>
</div>

app/views/municipality_residents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @municipality_resident %>

<div>
  <%= button_to "Editar", edit_municipality_resident_path(@municipality_resident), method: :get, class: "btn btn-warning" %>
  <%= button_to t("back_to_municipalities"), municipality_residents_path, method: :get, class: "btn btn-success" %>
</div>